name: MuhammadR_Resume

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '16'  # Use the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages  # Ensure this is the branch where your GitHub Pages site will be published
